name: intro_to_python

channels:
- conda-forge
- anaconda 

dependencies:
# Essential
- python==3.7.6
- nb_conda_kernels==2.2.0
- pip==19.3.1
- ipython==7.1.1
- tqdm==4.41.1
# Data Science
- numpy==1.18.1
- scipy==1.3.1
- pandas==0.25.3
# Machine Learning
- scikit-learn==0.22
- scikit-surprise==1.0.6
- umap-learn==0.4.2
# Visualization
- ipywidgets==7.4.2
- streamlit==1.2.0
- plotly==4.6.0
- matplotlib==3.1.2
- seaborn==0.9.0
# NLP
- nltk==3.4.1
- fuzzywuzzy==0.18.0
- pip:
  # Machine Learning
  - luwiji==1.1.4
